name: inspec-git-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install InSpec
      run: |
        wget https://packages.chef.io/files/stable/inspec/4.18.39/ubuntu/18.04/inspec_4.18.39-1_amd64.deb
        sudo dpkg -i inspec_4.18.39-1_amd64.deb
    - name: Running Python3 Inspec Profile
      run: |
        inspec exec . --chef-license accept --no-color
